server:
  port: 8010
spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5999/mydb
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: create

salt: 1234